<?php

define('MISSCHERRIES_THEME_VERSION', '0.1.202003051158');
define('MISSCHERRIES_THEME_STYLES_VERSION', MISSCHERRIES_THEME_VERSION);
define('MISSCHERRIES_THEME_SCRIPTS_VERSION', MISSCHERRIES_THEME_VERSION);
define('MISSCHERRIES_THEME_SLUG', 'misscherries');
